cooldowns: # В миллисекундах
  default:    500
  help:       150
  glide:      150
  gravity:    150
  resize:     150
  strength:   150
  health:     150
  banneredit: 300
  edit:       300
  freeze:     3500
  sneeze:     5000
  spit:       5000
  piss:       30000
  hideState:  1800000 # 30 минут

blocked-disguises:
  - interaction
  - unknown
  - lightning_bolt
  - marker
  - experience_orb

systems:
  logger: false
  edit: true
  paint: true
  decorationbanners: true
  decorationheads: true
  plot-edit: true
  plot-massclaim: true
