banner:
  post:
    default-limit: 18
    limits:
      "group.don_rise_perms": 45
      "group.don_flare_perms": 45
      "group.don_shine_perms": 90
      "group.don_spark_perms": 90
      "group.don_sunny_perms": 90
      "group.don_horizon_perms": 180
      "advancedcreative.decorationbanners.post_bypass": -1
  storage:
    default-limit: 18
    min-pages: 10
    page-size: 45
    limits:
      "group.don_rise_perms": 45
      "group.don_flare_perms": 45
      "group.don_shine_perms": 90
      "group.don_spark_perms": 90
      "group.don_sunny_perms": 90
      "group.don_horizon_perms": 180
      "advancedcreative.decorationbanners.storage_bypass": -1
