roles:
  player:
    display: "Player"
    prefix: "<#8C8C8C><b>É¢á´€á´á´‡Ê€</b>"
    permissions:
      - "acreative.ahelp"
      - "acreative.itemdb"
      - "acreative.sit"
      - "acreative.lay"
      - "acreative.crawl"
      - "acreative.hide"
      - "acreative.strength"
      - "acreative.health"
      - "acreative.effects"
      - "acreative.decorationheads"
      - "acreative.decorationbanners"
  rise:
    display: "<#24b2b2><b>Ê€ÉªÑ•á´‡</b>"
    rank-permissions:
      - "group.don_rise_perms"
    permissions:
      - "acreative.glide"
      - "acreative.gravity"
      - "acreative.sneeze"
      - "acreative.edit"
  flare:
    display: "<#21d185><b>êœ°ÊŸá´€Ê€á´‡</b>"
    rank-permissions:
      - "group.don_flare_perms"
    permissions:
      - "acreative.freeze"
      - "acreative.resize"
  shine:
    display: "<#9466ff><b>Ñ•ÊœÉªÉ´á´‡</b>"
    rank-permissions:
      - "group.don_shine_perms"
    permissions:
      - "acreative.paint"
  spark:
    display: "<#cd56fc><b>Ñ•á´˜á´€Ê€á´‹</b>"
    rank-permissions:
      - "group.don_spark_perms"
    permissions:
      - "acreative.glow"
      - "acreative.disguise"
  sunny:
    display: "<#ff7e33><b>Ñ•á´œÉ´É´Ê</b>"
    rank-permissions:
      - "group.don_sunny_perms"
    permissions:
      - "acreative.sithead"
  horizon:
    display: "<#ffcc00><b>Êœá´Ê€Éªá´¢á´É´</b>"
    rank-permissions:
      - "group.don_horizon_perms"
    permissions:
      - "acreative.spit"
      - "acreative.piss"
      - "acreative.disguise.nick"
      - "acreative.disguise.extended"
  moder:
    display: "Moder"
    prefix: "<#9C4804><b>á´<#AF5105>á´<#C25A05>á´…<#D56206>á´‡<#E86B06>Ê€</b>"
    rank-permissions:
      - "acreative.acreative"
    permissions:
      - "acreative.acreative"
      - "acreative.sithead.other"
      - "acreative.freeze.other"
      - "acreative.effects.other"
      - "acreative.hide.bypass"
      - "acreative.paint.bypass"
      - "acreative.paint.moderation"
      - "acreative.decorationbanners.storage_bypass"
      - "acreative.decorationbanners.post_bypass"
      - "acreative.decorationbanners.moderation"
      - "acreative.grab"
      - "acreative.slap"
      - "acreative.jar"

