roles:
  player:
    display: "Player"
    prefix: "<#8C8C8C><b>ɢᴀᴍᴇʀ</b>"
    permissions:
      - "acreative.ahelp"
      - "acreative.itemdb"
      - "acreative.sit"
      - "acreative.lay"
      - "acreative.crawl"
      - "acreative.hide"
      - "acreative.strength"
      - "acreative.health"
      - "acreative.effects"
      - "acreative.plots.edit"
      - "acreative.plots.usage"
      - "acreative.decorationheads"
      - "acreative.decorationbanners"
  rise:
    display: "<#24b2b2><b>ʀɪѕᴇ</b>"
    rank-permissions:
      - "group.don_rise_perms"
    permissions:
      - "acreative.glide"
      - "acreative.gravity"
      - "acreative.sneeze"
      - "acreative.edit"
  flare:
    display: "<#21d185><b>ꜰʟᴀʀᴇ</b>"
    rank-permissions:
      - "group.don_flare_perms"
    permissions:
      - "acreative.freeze"
      - "acreative.resize"
  shine:
    display: "<#9466ff><b>ѕʜɪɴᴇ</b>"
    rank-permissions:
      - "group.don_shine_perms"
    permissions:
      - "acreative.paint"
      - "acreative.plots.massclaim"
  spark:
    display: "<#cd56fc><b>ѕᴘᴀʀᴋ</b>"
    rank-permissions:
      - "group.don_spark_perms"
    permissions:
      - "acreative.glow"
      - "acreative.disguise"
  sunny:
    display: "<#ff7e33><b>ѕᴜɴɴʏ</b>"
    rank-permissions:
      - "group.don_sunny_perms"
    permissions:
      - "acreative.sithead"
  horizon:
    display: "<#ffcc00><b>ʜᴏʀɪᴢᴏɴ</b>"
    rank-permissions:
      - "group.don_horizon_perms"
    permissions:
      - "acreative.spit"
      - "acreative.piss"
      - "acreative.disguise.nick"
      - "acreative.disguise.extended"
  moder:
    display: "Moder"
    prefix: "<#9C4804><b>ᴍ<#AF5105>ᴏ<#C25A05>ᴅ<#D56206>ᴇ<#E86B06>ʀ</b>"
    rank-permissions:
      - "acreative.admin"
    permissions:
      - "acreative.admin"
      - "acreative.sithead.other"
      - "acreative.freeze.other"
      - "acreative.effects.other"
      - "acreative.plots.usage.other"
      - "acreative.plots.owner.manage"
      - "acreative.hide.bypass"
      - "acreative.paint.bypass"
      - "acreative.paint.moderation"
      - "acreative.decorationbanners.storage_bypass"
      - "acreative.decorationbanners.post_bypass"
      - "acreative.decorationbanners.moderation"
      - "acreative.disguise.player"
      - "acreative.disguise.text"
      - "acreative.grab"
      - "acreative.slap"
      - "acreative.jar"
