plotsquared:
  edit:
    plotEditAdminAccess: "acreative.admin"
    enabled-flags:
      - "time"
      - "weather"
      - "notify-enter"
      - "notify-leave"
      - "hide-info"
      - "feed"
      - "heal"
      - "beacon-effects"
      - "plot-paint"
      - "music"
      - "titles"
      - "plot-title"
      - "greeting"
      - "farewell"
      - "use"
      - "place"
      - "break"
      - "item-drop"
      - "edit-sign"
      - "device-interact"
      - "sculk-sensor-interact"
      - "concrete-harden"
      - "copper-oxide"
      - "redstone"
      - "deny-portals"
      - "animal-interact"
      - "animal-attack"
      - "animal-cap"
      - "tamed-interact"
      - "tamed-attack"
      - "villager-interact"
      - "mob-place"
      - "mob-cap"
      - "entity-cap"
      - "entity-change-block"
      - "hostile-interact"
      - "hostile-attack"
      - "hostile-cap"
      - "pve"
      - "crop-grow"
      - "grass-grow"
      - "kelp-grow"
      - "vine-grow"
      - "mycel-grow"
      - "leaf-decay"
      - "soil-dry"
      - "coral-dry"
      - "ice-form"
      - "ice-melt"
      - "snow-form"
      - "snow-melt"
      - "liquid-flow"
      - "disable-physics"
      - "block-burn"
      - "block-ignition"
      - "vehicle-use"
      - "vehicle-place"
      - "vehicle-break"
      - "vehicle-cap"
      - "misc-interact"
      - "misc-place"
      - "misc-break"
      - "misc-cap"
      - "hanging-place"
      - "hanging-break"
      - "instabreak"
      - "weaving-death-place"
      - "drop-protection"
      - "fishing"
      - "projectiles"
      - "fly"
      - "gamemode"
      - "guest-gamemode"
      - "invincible"
      - "no-worldedit"
      - "tile-drop"
      - "forcefield"
      - "redstone-clock"
      - "deny-exit"
      - "blocked-cmds"
      - "server-plot"
    role-flags:
      player:
        - "time"
        - "weather"
        - "notify-enter"
        - "notify-leave"
        - "hide-info"
        - "feed"
        - "heal"
        - "beacon-effects"
        - "plot-paint"
      rise:
        - "music"
        - "titles"
        - "plot-title"
        - "greeting"
        - "farewell"
        - "use"
        - "place"
        - "break"
        - "item-drop"
        - "edit-sign"
        - "device-interact"
        - "sculk-sensor-interact"
        - "concrete-harden"
        - "copper-oxide"
        - "redstone"
        - "deny-portals"
      flare:
        - "animal-interact"
        - "animal-attack"
        - "animal-cap"
        - "tamed-interact"
        - "tamed-attack"
        - "villager-interact"
        - "mob-place"
        - "mob-cap"
        - "entity-cap"
        - "entity-change-block"
        - "hostile-interact"
        - "hostile-attack"
        - "hostile-cap"
        - "pve"
        - "crop-grow"
        - "grass-grow"
        - "kelp-grow"
        - "vine-grow"
        - "mycel-grow"
        - "leaf-decay"
        - "soil-dry"
        - "coral-dry"
        - "ice-form"
        - "ice-melt"
        - "snow-form"
        - "snow-melt"
        - "liquid-flow"
        - "disable-physics"
        - "block-burn"
        - "block-ignition"
      shine:
        - "vehicle-use"
        - "vehicle-place"
        - "vehicle-break"
        - "vehicle-cap"
        - "misc-interact"
        - "misc-place"
        - "misc-break"
        - "misc-cap"
        - "hanging-place"
        - "hanging-break"
        - "instabreak"
        - "weaving-death-place"
      spark:
        - "drop-protection"
        - "fishing"
        - "projectiles"
        - "fly"
        - "gamemode"
        - "guest-gamemode"
        - "invincible"
      sunny:
        - "no-worldedit"
      horizon:
        - "tile-drop"
        - "forcefield"
      moder:
        - "redstone-clock"
        - "deny-exit"
        - "blocked-cmds"
        - "server-plot"

